services:
  frontend-mediclick:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend-mediclick
    ports:
      - "3090:80"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://159.223.200.169:4080/api/v1
    restart: unless-stopped